### PR TITLE
Add WSL detection

### PR DESCRIPTION
**Pull request by GustavoLCR**

### CODE REVIEW

**Comment by radare** [comment]
Wtf??? You have to edit the configure.acr not this script

**Comment by GustavoLCR** [comment]
Yeah, but I didn't see a way to detect wsl and disable ptrace-wrap automatically. With this I can add in the configure.acr:
`IFEQ USEROSTYPE wsl ; {`
`       HAVE_PTRACE = 1 ;`
`       USE_PTRACE_WRAP = 0 ;`
`}`

**Comment by radare** [comment]
Can you do a pr?

**Comment by GustavoLCR** [comment]
@radare can you check this one again?

**Pull request merged**
